#!/bin/bash

CXD=$(dirname $(realpath $0))
pCXD=$(dirname $CXD)
SRC=$pCXD/src
ZCTX=$SRC/zctx

chmod a+w                              $SRC/zctx.py 2> /dev/null
cat $ZCTX/std.py                    >  $SRC/zctx.py
cat $ZCTX/defs.py                   >> $SRC/zctx.py
cat $ZCTX/ZCE/ZCEs.py               >> $SRC/zctx.py
cat $ZCTX/p-cpl1.py                 >> $SRC/zctx.py
cat $ZCTX/zctx.py                   >> $SRC/zctx.py
cat $ZCTX/ext.py                    >> $SRC/zctx.py
cat $ZCTX/p-cpl2.py                 >> $SRC/zctx.py
cat $ZCTX/output1.py                >> $SRC/zctx.py
cat $ZCTX/ZCE/type.py               >> $SRC/zctx.py
cat $ZCTX/parsing.py                >> $SRC/zctx.py
cat $ZCTX/output2.py                >> $SRC/zctx.py
cat $ZCTX/ZCE/datItm.py             >> $SRC/zctx.py
cat $ZCTX/ZCE/fct.py                >> $SRC/zctx.py
cat $ZCTX/ZCE/ope.py                >> $SRC/zctx.py
cat $ZCTX/pfx.py                    >> $SRC/zctx.py
cat $ZCTX/read/generic.py           >> $SRC/zctx.py
cat $ZCTX/read/type.py              >> $SRC/zctx.py
cat $ZCTX/read/value_ODP.py         >> $SRC/zctx.py
cat $ZCTX/read/value_2ndAnalysis.py >> $SRC/zctx.py
cat $ZCTX/read/value.py             >> $SRC/zctx.py
cat $ZCTX/read/dataItem.py          >> $SRC/zctx.py
chmod a-w                              $SRC/zctx.py
