#!/bin/bash

cat zctx/std.py            >  zctx.py
cat zctx/defs.py           >> zctx.py
cat zctx/generic.py        >> zctx.py
cat zctx/ZCEs.py           >> zctx.py
cat zctx/p-cpl1.py         >> zctx.py
cat zctx/zctx.py           >> zctx.py
cat zctx/p-cpl2.py         >> zctx.py
cat zctx/output1.py        >> zctx.py
cat zctx/parsing.py        >> zctx.py
cat zctx/output2.py        >> zctx.py
cat zctx/read/generic.py   >> zctx.py
cat zctx/read/type.py      >> zctx.py
cat zctx/read/value.py     >> zctx.py
cat zctx/read/dataItem.py  >> zctx.py
