#!/bin/bash

CXD=$(dirname $(realpath $0))

chmod a+w                          $CXD/zctx.py
cat $CXD/zctx/std.py            >  $CXD/zctx.py
cat $CXD/zctx/defs.py           >> $CXD/zctx.py
cat $CXD/zctx/independant.py    >> $CXD/zctx.py
cat $CXD/zctx/ZCEs.py           >> $CXD/zctx.py
cat $CXD/zctx/p-cpl1.py         >> $CXD/zctx.py
cat $CXD/zctx/zctx.py           >> $CXD/zctx.py
cat $CXD/zctx/p-cpl2.py         >> $CXD/zctx.py
cat $CXD/zctx/output1.py        >> $CXD/zctx.py
cat $CXD/zctx/parsing.py        >> $CXD/zctx.py
cat $CXD/zctx/output2.py        >> $CXD/zctx.py
cat $CXD/zctx/read/generic.py   >> $CXD/zctx.py
cat $CXD/zctx/read/type.py      >> $CXD/zctx.py
cat $CXD/zctx/read/value.py     >> $CXD/zctx.py
cat $CXD/zctx/read/dataItem.py  >> $CXD/zctx.py
chmod a-w                          $CXD/zctx.py
